const assert = require('node:assert/strict');
const fs = require('node:fs');
const {JSDOM} = require('jsdom');
const html = fs.readFileSync(process.cwd()+'/examples/general_agent/chat.html','utf8');
const script = html.match(/<script>([\s\S]*?)<\/script>/)[1].replace(/\n\s*initialize\(\);\s*$/, '');
const dom = new JSDOM(html,{url:'http://127.0.0.1:8771/',runScripts:'outside-only'});
const w=dom.window;
w.setTimeout=()=>0;
w.clearTimeout=()=>{};
w.matchMedia=()=>({matches:false});
w.eval(script+'\nwindow.check={state,handle,renderConnections,selectChat,syncCurrentChat};');
const {state,handle,renderConnections,selectChat,syncCurrentChat}=w.check;
const doc=w.document;
function descriptors(status){return [{id:'shared',name:'Environment',kind:'browser',status,preview:{transport:'frames',media_type:'image/png'}}];}
(async()=>{
 state.chat={id:'a',title:'Chat A'};
 state.connections=descriptors('configured');
 renderConnections();
 handle({type:'connections',chat_id:'b',connections:descriptors('B connected')});
 assert.match(doc.querySelector('#connections').textContent,/configured/);
 assert.doesNotMatch(doc.querySelector('#connections').textContent,/B connected/);
 handle({type:'connections',chat_id:'a',connections:[...descriptors('A connected'),...['image/png','video/mp4','audio/wav','application/pdf'].map((media,i)=>({id:'resource'+i,name:'Resource '+i,selectable:false,preview:{media_type:media,url:'/resource/'+i}}))]});
 assert.match(doc.querySelector('#connections').textContent,/A connected/);
 assert.equal(doc.querySelectorAll('#connections video').length,1);
 assert.equal(doc.querySelectorAll('#connections audio').length,1);
 assert.equal(doc.querySelectorAll('#connections img').length,2);
 assert.equal(doc.querySelectorAll('#connections a.file-chip').length,1);
 const activeImage=state.previewImages.get('shared');
 handle({type:'frame',chat_id:'b',connection_id:'shared',data:'B_FRAME'});
 assert.equal(activeImage.getAttribute('src'),null);
 handle({type:'frame',chat_id:'a',connection_id:'shared',data:'A_FRAME'});
 assert.equal(activeImage.getAttribute('src'),'data:image/png;base64,A_FRAME');
 state.chat={id:'b',title:'Chat B'};renderConnections();
 assert.match(doc.querySelector('#connections').textContent,/B connected/);
 assert.equal(state.previewImages.get('shared').getAttribute('src'),'data:image/png;base64,B_FRAME');
 state.chat={id:'a',title:'Chat A'};
 let release;
 w.fetch=()=>new Promise(resolve=>{release=data=>resolve({ok:true,json:async()=>data});});
 const load=selectChat('b');
 handle({type:'message',chat_id:'b',message:{id:'u',role:'user',text:'Request',status:'completed',created_at:1}});
 handle({type:'message',chat_id:'b',message:{id:'r',role:'assistant',text:'Fresh response',status:'completed',created_at:2}});
 handle({type:'message',chat_id:'a',message:{id:'other',role:'user',text:'Other chat',created_at:3}});
 handle({type:'busy',chat_id:'b',busy:false});
 release({chat:{id:'b',title:'Chat B',status:'running'},messages:[{id:'u',role:'user',text:'Request',status:'queued',created_at:1}]});
 await load;
 assert.equal(state.chat.id,'b');
 assert.equal(state.messages.size,2);
 assert.equal(state.messages.get('u').status,'completed');
 assert.equal(state.messages.get('r').text,'Fresh response');
 assert.equal(state.messages.has('other'),false);
 assert.equal(state.busy.get('b'),false);
 assert.equal(state.transcriptReads.size,0);
 const syncing=syncCurrentChat();
 handle({type:'message',chat_id:'b',message:{id:'r',role:'assistant',text:'Revised response',status:'completed',created_at:2}});
 handle({type:'busy',chat_id:'b',busy:false});
 release({chat:{id:'b',title:'Chat B',status:'running'},messages:[{id:'r',role:'assistant',text:'Stale response',status:'queued',created_at:2}]});
 await syncing;
 assert.equal(state.messages.get('r').text,'Revised response');
 assert.equal(state.messages.size,2);
 assert.equal(state.busy.get('b'),false);
 assert.equal(state.syncing,false);
 assert.equal(state.transcriptReads.size,0);
 // A rejected read must release its event buffer and allow later reconnects.
 w.fetch=async()=>{throw new Error('test disconnect');};
 await assert.rejects(syncCurrentChat(),/test disconnect/);
 assert.equal(state.transcriptReads.size,0);
 assert.equal(state.syncing,false);
 console.log('PASS: scoped connection status and frames, 4 preview media types, selection/reconnect SSE races, message dedupe, failed-read cleanup');
 dom.window.close();
})().catch(error=>{console.error(error);process.exitCode=1;dom.window.close();});
