[tool.poetry]
name = "prompt-optimization"
version = "0.1.0"
description = ""
authors = ["Jacob Valdez <jacob@deepshard.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
