"""Explicit action execution and observation-driven model-policy replanning.

Text generated by a planner is inert. Applications explicitly construct structured
plans and provide both an action registry and a policy that consumes observations.
"""
from __future__ import annotations

from copy import deepcopy
from dataclasses import asdict, dataclass, field
import inspect
import json
import math
import os
import tempfile
from pathlib import Path
from types import MappingProxyType
from typing import Any, Callable, Mapping
import uuid

from ...tools.actions import ActionOutcome


def _json(value):
    """Copy strictly JSON data without coercing tuples, keys, or custom objects."""
    if value is None or type(value) in (str, bool, int):
        return value
    if type(value) is float and math.isfinite(value):
        return value
    if type(value) is list:
        return [_json(item) for item in value]
    if type(value) is dict and all(type(key) is str for key in value):
        return {key: _json(item) for key, item in value.items()}
    raise ValueError('trajectory values must use finite JSON types and string keys')


def _text(value):
    return type(value) is str and bool(value.strip())


def _unique_object(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError('duplicate trajectory field')
        result[key] = value
    return result


@dataclass(frozen=True)
class PlanStep:
    action: str
    arguments: dict = field(default_factory=dict)
    expected_observation: Any = None


@dataclass(frozen=True)
class ExecutablePlan:
    candidate_id: str
    steps: tuple[PlanStep, ...]


@dataclass(frozen=True)
class OutcomeExperience:
    candidate_id: str
    action: str
    source_id: str
    observation: Any
    status: str
    arguments: dict = field(default_factory=dict)
    expected_observation: Any = None

    def to_target(self, outcome):
        """Attach an explicit retrospective label only to the observed candidate."""
        if isinstance(outcome, bool) or not isinstance(outcome, (int, float)) or not math.isfinite(outcome):
            raise ValueError('outcome must be a finite observed numeric label')
        return {'candidate_id': self.candidate_id, 'outcome': outcome}

    def as_evidence(self):
        return {'source_id': self.source_id, 'text': json.dumps(
            {'action': self.action, 'status': self.status, 'observation': self.observation},
            sort_keys=True, allow_nan=False)}


@dataclass(frozen=True)
class ReplanRequest:
    state: Any
    previous_plan: ExecutablePlan
    experiences: tuple[OutcomeExperience, ...]
    step: int

    @property
    def evidence(self):
        return [item.as_evidence() for item in self.experiences]


@dataclass(frozen=True)
class PlanExecutionResult:
    state: Any
    experiences: tuple[OutcomeExperience, ...]
    stop_reason: str
    policy_errors: tuple[str, ...] = ()

    def save(self, path):
        """Atomically persist validated JSON data, without executable code."""
        if type(self.experiences) is not tuple or any(not isinstance(item, OutcomeExperience) for item in self.experiences):
            raise ValueError('experiences must be a tuple of OutcomeExperience records')
        if type(self.policy_errors) is not tuple:
            raise ValueError('policy_errors must be a tuple of strings')
        data = {'version': 1, 'state': self.state,
                'experiences': [asdict(item) for item in self.experiences],
                'stop_reason': self.stop_reason, 'policy_errors': list(self.policy_errors)}
        self._from_data(data)
        encoded = json.dumps(data, allow_nan=False)
        target = Path(path)
        temporary = None
        try:
            with tempfile.NamedTemporaryFile(mode='w', encoding='utf-8',
                    dir=target.parent, prefix='.' + target.name + '-', delete=False) as stream:
                temporary = Path(stream.name)
                stream.write(encoded)
                stream.flush()
                os.fsync(stream.fileno())
            os.replace(temporary, target)
        finally:
            if temporary is not None:
                temporary.unlink(missing_ok=True)

    @classmethod
    def _from_data(cls, data):
        data = _json(data)
        required = {'version', 'state', 'experiences', 'stop_reason', 'policy_errors'}
        if type(data) is not dict or set(data) != required:
            raise ValueError('invalid trajectory fields')
        if type(data['version']) is not int or data['version'] != 1:
            raise ValueError('unsupported trajectory version')
        reason = data['stop_reason']
        if type(reason) is not str or reason not in {'completed', 'abstained', 'policy_error', 'budget_exhausted'}:
            raise ValueError('invalid trajectory stop_reason')
        errors = data['policy_errors']
        if type(errors) is not list or any(not _text(item) for item in errors):
            raise ValueError('policy_errors must be a list of nonempty strings')
        if bool(errors) != (reason == 'policy_error'):
            raise ValueError('policy errors must agree with stop_reason')
        records = data['experiences']
        if type(records) is not list:
            raise ValueError('experiences must be a list')
        required_record = {'candidate_id', 'action', 'source_id', 'observation',
                           'status', 'arguments', 'expected_observation'}
        experiences, ids = [], set()
        for item in records:
            if type(item) is not dict or set(item) != required_record:
                raise ValueError('invalid action experience fields')
            if any(not _text(item[key]) for key in ('candidate_id', 'action', 'source_id')):
                raise ValueError('action experience IDs and action must be nonempty strings')
            if item['source_id'] in ids:
                raise ValueError('trajectory requires unique observation source IDs')
            ids.add(item['source_id'])
            if type(item['status']) is not str or item['status'] not in ('observed', 'error'):
                raise ValueError('invalid action experience status')
            if type(item['arguments']) is not dict:
                raise ValueError('experience arguments must be a JSON object')
            if item['status'] == 'error':
                error = item['observation']
                if (type(error) is not dict or set(error) != {'error_type', 'message'}
                        or not _text(error['error_type']) or type(error['message']) is not str):
                    raise ValueError('error observations require error_type and message')
            experiences.append(OutcomeExperience(**item))
        if reason != 'budget_exhausted' and not experiences:
            raise ValueError('stop_reason requires an action observation')
        if reason == 'completed' and experiences[-1].status != 'observed':
            raise ValueError('completed trajectories require a final observed outcome')
        return cls(data['state'], tuple(experiences), reason, tuple(errors))

    @classmethod
    def load(cls, path):
        data = json.loads(Path(path).read_text(encoding='utf-8'), object_pairs_hook=_unique_object)
        return cls._from_data(data)


class PlanExecutor:
    """Execute one validated step, observe, and ask the policy for a new plan.

    Registry actions accept ``(state, **arguments)`` and return ActionOutcome.
    Failures are observations; external effects cannot be rolled back. The policy
    must explicitly select subsequent actions; there is no first-action fallback.
    Input state is copied; only returned ActionOutcome state advances the run.
    """

    def __init__(self, *, actions: Mapping[str, Callable], replan: Callable,
                 max_steps: int):
        if not callable(replan):
            raise TypeError('replan must be an explicit callable policy')
        if type(max_steps) is not int or max_steps < 0:
            raise ValueError('max_steps must be a nonnegative integer')
        actions = dict(actions)
        if any(not _text(name) or not callable(fn) for name, fn in actions.items()):
            raise ValueError('actions must map nonempty names to callables')
        self.actions = MappingProxyType(actions)
        self.replan, self.max_steps = replan, max_steps

    def validate(self, plan):
        if not isinstance(plan, ExecutablePlan):
            raise TypeError('policy must return an explicit ExecutablePlan; generated text is inert')
        if not _text(plan.candidate_id):
            raise ValueError('plan requires a candidate_id')
        if not isinstance(plan.steps, (tuple, list)) or not plan.steps:
            raise ValueError('plan requires explicit nonempty steps')
        for step in plan.steps:
            if not isinstance(step, PlanStep) or not _text(step.action) or step.action not in self.actions:
                raise ValueError('every step must name an explicitly registered action')
            if not isinstance(step.arguments, dict) or any(not isinstance(k, str) for k in step.arguments):
                raise ValueError('step arguments must be a JSON object')
            _json(step.arguments)
            _json(step.expected_observation)
            inspect.signature(self.actions[step.action]).bind(None, **step.arguments)
        return deepcopy(plan)

    def __call__(self, state, plan):
        plan = self.validate(plan)  # Validate the entire initial plan before effects.
        state = _json(state)
        experiences = []
        for index in range(self.max_steps):
            step = plan.steps[0]
            try:
                outcome = self.actions[step.action](deepcopy(state), **deepcopy(step.arguments))
                if not isinstance(outcome, ActionOutcome) or type(outcome.done) is not bool:
                    raise TypeError('action must return ActionOutcome with boolean done')
                next_state, observation = _json(outcome.state), _json(outcome.receipt)
                state = next_state
                status, done = 'observed', outcome.done
            except Exception as exc:
                observation = {'error_type': type(exc).__name__, 'message': str(exc)}
                status, done = 'error', False
            experiences.append(OutcomeExperience(plan.candidate_id, step.action,
                'action:' + uuid.uuid4().hex, observation, status,
                deepcopy(step.arguments), deepcopy(step.expected_observation)))
            if done:
                return PlanExecutionResult(state, tuple(experiences), 'completed')
            if index + 1 == self.max_steps:
                break
            request = ReplanRequest(deepcopy(state), deepcopy(plan), deepcopy(tuple(experiences)), index + 1)
            try:
                proposed = self.replan(request)
                if proposed is None:
                    return PlanExecutionResult(state, tuple(experiences), 'abstained')
                plan = self.validate(proposed)
            except Exception as exc:
                return PlanExecutionResult(state, tuple(experiences), 'policy_error',
                                           (f'{type(exc).__name__}: {exc}',))
        return PlanExecutionResult(state, tuple(experiences), 'budget_exhausted')
