"""The assistant's procedures, as data.

Each one is a list of guarded steps: look before acting, act, read the result back, then
say only what was observed. Sub-procedures (``resolve``, ``open_path``, ``verify_file``)
are called with ``call`` and hand values back with ``return``, so the same work is written
once. ``say`` may carry ``"and": "stop"`` (end the request) or ``"and": "return"`` (leave
the sub-procedure) instead of repeating a guard on the next line.

Nothing here is Python: every procedure round-trips through JSON (see tests), and a
learned skill is the same kind of object with ``author="learned-from-trace"``.
"""

from __future__ import annotations

from .procedure import HOME, Procedure

STAT = "stat -c '%F|%s|%n' {path|q}"

PROCEDURES: list[Procedure] = [

    # ------------------------------------------------------------- talking
    Procedure(id="greet", act="greet", steps=[
        {"do": "say", "text": "Hi! I'm driving this Ubuntu desktop for you. Ask me to do something with your files or the machine, or say “help”."},
    ]),
    Procedure(id="thanks", act="thanks", steps=[{"do": "say", "text": "You're welcome."}]),
    Procedure(id="help", act="help", steps=[{"do": "say", "text": """Things you can ask me (I work this Ubuntu machine through its screen, no AI model):
• files: “make a folder called recipes on my desktop”, “create notes.txt in it saying hello”, “add 'buy milk' to notes.txt”, “read notes.txt”
• look around: “what's on my desktop?”, “find all pdfs”, “which files mention dns?”, “how big is my documents folder?”
• change things: “rename notes.txt to ideas.txt”, “move it to documents”, “copy it to the desktop”, “delete it”
• git: “make recipes a git repo”, “commit everything in recipes as 'first'”, “what changed in recipes?”, “show its history”
• the machine: “what time is it?”, “how much disk space is left?”, “what's my ip?”, “what's running?”, “open firefox”
• anything else: run a command with backticks, like `ls -la ~`
You can chain requests with “then”."""}]),
    Procedure(id="unknown", act="unknown", steps=[
        {"do": "call", "proc": "admit", "with": {"kind": "not_understood", "what": "{words}"}, "bind": {}},
    ]),
    Procedure(id="stray_yes_no", act="confirm", steps=[
        {"do": "say", "text": "There's nothing waiting for a yes or no right now."},
    ]),
    Procedure(id="stray_cancel", act="cancel", steps=[
        {"do": "say", "text": "There's nothing waiting for a yes or no right now."},
    ]),
    Procedure(id="stray_choice", act="choose", steps=[
        {"do": "compute", "prim": "bare_path", "args": {"words": "{words}"}},
        {"when": {"truthy": "{is_path}"}, "do": "call", "proc": "read", "with": {"slot": {"target": "{path_text}"}}, "bind": {}},
        {"when": {"truthy": "{is_path}"}, "do": "stop"},
        {"do": "say", "text": "There's no open question right now."},
    ]),

    # --------------------------------------------------- resolving a name
    Procedure(id="resolve", takes=["ref", "want", "place", "what"], returns=["path"], steps=[
        {"when": {"missing": "{ref}"}, "do": "say", "text": "Which {what} do you mean? I didn't catch a name.", "and": "return"},
        {"when": {"all": [{"eq": ["{ref}", "@it"]}, {"missing": "{focus}"}]}, "do": "say",
         "text": "I'm not sure what “it” refers to yet. Tell me the {what} by name.", "and": "return"},
        {"when": {"eq": ["{ref}", "@it"]}, "do": "return", "values": {"path": "{focus}"}},
        {"do": "compute", "prim": "strip_ref", "args": {"ref": "{ref}"}},
        {"when": {"exists": "{place_path}"}, "do": "compute", "prim": "expand", "args": {"path": "{place_path}", "cwd": "{cwd}"}},
        {"when": {"exists": "{place_path}"}, "do": "return", "values": {"path": "{path}"}},
        {"when": {"truthy": "{looks_like_path}"}, "do": "compute", "prim": "expand", "args": {"path": "{name}", "cwd": "{cwd}"}},
        {"when": {"truthy": "{looks_like_path}"}, "do": "return", "values": {"path": "{path}"}},
        {"do": "compute", "prim": "candidates", "args": {"name": "{name}", "place": "{place}", "cwd": "{cwd}", "known": "{known}"}},
        {"do": "run", "command": "stat -c '%F|%s|%n' {candidates|qlist}", "why": "look for {name} before acting"},
        {"do": "compute", "prim": "stat_map", "args": {"out": "{out}"}},
        {"do": "compute", "prim": "hits", "args": {"stats": "{stats}", "candidates": "{candidates}", "want": "{want}",
                                                   "place": "{place}", "known": "{known}"}},
        {"when": {"truthy": "{settled}"}, "do": "compute", "prim": "at", "args": {"items": "{hits}", "index": 0}},
        {"when": {"truthy": "{settled}"}, "do": "return", "values": {"path": "{item}"}},
        {"when": {"falsy": "{hits}"}, "do": "compute", "prim": "find_flag", "args": {"want": "{want}"}},
        {"when": {"falsy": "{hits}"}, "do": "run", "command": "find " + HOME + " -name {name|q}{find_flag} 2>/dev/null | head -n 40",
         "why": "search the home folder for {name}"},
        {"when": {"falsy": "{hits}"}, "do": "compute", "prim": "paths_in_output", "args": {"out": "{out}", "limit": 40}},
        {"when": {"falsy": "{hits}"}, "do": "compute", "prim": "text_or", "args": {"value": "{place}", "fallback": "{cwd}"}, "as": "look"},
        {"when": {"falsy": "{hits}"}, "do": "compute", "prim": "expand", "args": {"path": "{look_text}", "cwd": "{cwd}"}, "as": "near"},
        {"when": {"falsy": "{hits}"}, "do": "run", "command": "ls -1pA {near_path|q}", "why": "see what is there instead", "as": "sib"},
        {"when": {"falsy": "{hits}"}, "do": "compute", "prim": "ls_facts", "args": {"out": "{sib_out}"}, "as": "there"},
        {"when": {"falsy": "{hits}"}, "do": "compute", "prim": "near_misses",
         "args": {"name": "{name}", "names": "{there_names}", "known": "{known}"}},
        # nothing near in the folder they meant: widen by prefix before giving up, because a
        # misspelling is still a near miss when the file lives somewhere else
        {"when": {"all": [{"falsy": "{hits}"}, {"falsy": "{n_near}"}]}, "do": "compute", "prim": "name_stem",
         "args": {"name": "{name}"}},
        {"when": {"all": [{"falsy": "{hits}"}, {"falsy": "{n_near}"}, {"truthy": "{stem_wide}"}]}, "do": "run",
         "command": "find " + HOME + " -maxdepth 4 -iname {stem_glob|q} 2>/dev/null | head -n 40",
         "why": "look for something like {name} elsewhere", "as": "wide"},
        {"when": {"all": [{"falsy": "{hits}"}, {"falsy": "{n_near}"}, {"truthy": "{stem_wide}"}]}, "do": "compute", "prim": "basenames",
         "args": {"out": "{wide_out}", "names": "{there_names}"}},
        {"when": {"all": [{"falsy": "{hits}"}, {"falsy": "{n_near}"}, {"truthy": "{stem_wide}"}]}, "do": "compute", "prim": "near_misses",
         "args": {"name": "{name}", "names": "{pool}", "known": "{known}"}},
        {"when": {"all": [{"falsy": "{hits}"}, {"truthy": "{n_near}"}]}, "do": "say",
         "text": "There's no {name} — did you mean {near_joined}?", "and": "return"},
        {"when": {"falsy": "{hits}"}, "do": "say", "text": "I couldn't find anything called “{name}” in your home folder.", "and": "return"},
        {"when": {"eq": ["{n_hits}", 1]}, "do": "compute", "prim": "at", "args": {"items": "{hits}", "index": 0}},
        {"when": {"eq": ["{n_hits}", 1]}, "do": "return", "values": {"path": "{item}"}},
        {"do": "compute", "prim": "options", "args": {"hits": "{hits}"}},
        {"do": "ask", "text": "I found {n_hits} things called “{name}”. Which one?\n{options|numbered}"},
        {"do": "compute", "prim": "choice", "args": {"answer": "{answer}", "options": "{options}"}},
        {"when": {"missing": "{pick}"}, "do": "say", "text": "Okay, I'll leave it.", "and": "return"},
        {"do": "compute", "prim": "at", "args": {"items": "{hits}", "index": "{pick}"}},
        {"do": "return", "values": {"path": "{item}"}},
    ]),

    # -------------------------------- a goal that is underdetermined, not unknown
    # "organize my desktop" is understood; what is missing is which way. Asking is priced
    # against guessing (tensacode.social.ask_or_act), so a clear request is never questioned.
    Procedure(id="clarify_goal", act="clarify_goal", steps=[
        {"do": "compute", "prim": "text_or", "args": {"value": "{slot.place}", "fallback": "{cwd}"}, "as": "where"},
        {"do": "call", "proc": "resolve", "with": {"ref": "{where_text}", "want": "directory", "what": "folder"}, "bind": {"path": "path"}},
        {"when": {"missing": "{path}"}, "do": "stop"},
        # "organize my pictures" presupposes there is a pictures folder; if there is not, the
        # honest reply corrects that belief rather than calling a missing folder empty
        {"do": "run", "command": STAT, "why": "check {path|show} is really there", "as": "st"},
        {"do": "compute", "prim": "stat_map", "args": {"out": "{st_out}"}},
        {"do": "compute", "prim": "kind_of", "args": {"stats": "{stats}", "path": "{path}"}},
        {"when": {"missing": "{kind}"}, "do": "say", "text": "There's no {path|show} — so there's nothing there to organize.", "and": "stop"},
        {"do": "run", "command": "ls -1pA {path|q}", "why": "see what is in {path|show} before asking", "as": "listing"},
        {"do": "compute", "prim": "ls_facts", "args": {"out": "{listing_out}"}},
        {"when": {"falsy": "{n_names}"}, "do": "say", "text": "{path|show} is already empty — nothing to organize.", "and": "stop"},
        {"do": "compute", "prim": "goal_options", "args": {"goal": "{words}", "names": "{names}"}},
        {"do": "ask", "text": "{path|show} has {n_names} item{n_names|s}. How would you like it organized?\n{options_numbered}"},
        {"do": "compute", "prim": "choice", "args": {"answer": "{answer}", "options": "{options}"}},
        {"when": {"missing": "{pick}"}, "do": "say", "text": "Okay, I'll leave it as it is.", "and": "stop"},
        {"when": {"eq": ["{pick}", 2]}, "do": "call", "proc": "open_path", "with": {"path": "{path}"}, "bind": {}},
        {"when": {"eq": ["{pick}", 2]}, "do": "stop"},
        {"when": {"eq": ["{pick}", 1]}, "do": "call", "proc": "admit",
         "with": {"kind": "cannot", "what": "{words}",
                  "needs": "I can only read names from the folder listing, not modification dates, so I can't group by month yet."}, "bind": {}},
        {"when": {"eq": ["{pick}", 1]}, "do": "stop"},
        {"do": "compute", "prim": "organize_command", "args": {"path": "{path}", "names": "{names}", "how": "by_type"}},
        {"when": {"falsy": "{n_moved}"}, "do": "say", "text": "There are no files to group in {path|show} — only folders.", "and": "stop"},
        {"do": "run", "command": "{command}", "why": "group {n_moved} files by kind", "as": "did"},
        {"do": "run", "command": "ls -1pA {path|q}", "why": "check what {path|show} looks like now", "as": "after"},
        {"do": "compute", "prim": "ls_facts", "args": {"out": "{after_out}"}, "as": "now"},
        {"do": "say", "text": "Grouped {n_moved} file{n_moved|s} into {n_groups} folder{n_groups|s} by kind in {path|show}: {groups_joined}. It now holds {now_n_names} item{now_n_names|s}."},
    ]),

    # ------------------------------------------------------ looking at things
    Procedure(id="list", act="list", steps=[
        {"do": "compute", "prim": "text_or", "args": {"value": "{slot.place}", "fallback": "{cwd}"}, "as": "where"},
        {"do": "call", "proc": "resolve", "with": {"ref": "{where_text}", "what": "folder"}, "bind": {"path": "path"}},
        {"when": {"missing": "{path}"}, "do": "stop"},
        {"do": "call", "proc": "open_path", "with": {"path": "{path}", "count": "{slot.count}"}, "bind": {}},
    ]),
    Procedure(id="read", act="read", steps=[
        {"do": "call", "proc": "resolve", "with": {"ref": "{slot.target}", "place": "{slot.place}", "what": "file"}, "bind": {"path": "path"}},
        {"when": {"missing": "{path}"}, "do": "stop"},
        {"do": "call", "proc": "open_path", "with": {"path": "{path}"}, "bind": {}},
    ]),
    Procedure(id="open_path", takes=["path", "count"], steps=[
        {"do": "run", "command": STAT, "why": "look at {path|show}", "as": "st"},
        {"do": "compute", "prim": "stat_map", "args": {"out": "{st_out}"}},
        {"do": "compute", "prim": "kind_of", "args": {"stats": "{stats}", "path": "{path}"}},
        {"when": {"missing": "{kind}"}, "do": "say", "text": "There's no {path|show}.", "and": "return"},
        {"when": {"is": ["{kind}", "directory"]}, "do": "call", "proc": "list_dir", "with": {"path": "{path}", "count": "{count}"}, "bind": {}},
        {"when": {"is": ["{kind}", "directory"]}, "do": "return", "values": {}},
        {"do": "call", "proc": "show_file", "with": {"path": "{path}"}, "bind": {}},
    ]),
    Procedure(id="list_dir", takes=["path", "count"], steps=[
        {"do": "run", "command": "ls -1pA {path|q}", "why": "list {path|show}"},
        {"when": {"falsy": "{ok}"}, "do": "say", "text": "I couldn't list {path|show}: {error_summary}", "and": "return"},
        {"do": "compute", "prim": "ls_facts", "args": {"out": "{out}"}},
        {"do": "focus", "path": "{path}", "kind": "directory"},
        {"when": {"truthy": "{count}"}, "do": "say",
         "text": "{path|show} has {n_names|plural:item} ({folders|plural:folder}, {files|plural:file}).", "and": "return"},
        {"when": {"falsy": "{names}"}, "do": "say", "text": "{path|show} is empty.", "and": "return"},
        {"do": "say", "text": "{path|show} has {n_names} item{n_names|s}: {names|listing}"},
    ]),
    Procedure(id="show_file", takes=["path"], steps=[
        {"do": "run", "command": "head -n 40 {path|q}", "why": "read {path|show}"},
        {"do": "focus", "path": "{path}", "kind": "regular file"},
        {"when": {"falsy": "{ok}"}, "do": "say", "text": "I couldn't read {path|show}: {error_summary}", "and": "return"},
        {"do": "compute", "prim": "head_limit", "args": {"out": "{out}", "limit": 40}},
        {"when": {"truthy": "{blank}"}, "do": "say", "text": "{path|show} is empty.", "and": "return"},
        {"do": "say", "text": "{path|show} says{more}:\n{out|trim}"},
    ]),

    # ------------------------------------------------- answering, not acting
    #
    # A question is a procedure too: its steps query memory (``recall``) or a modality
    # (``sample``) instead of running a command, and every answer names where it came from.

    # three different failures, told apart: not understood / can't / don't know
    Procedure(id="admit", takes=["kind", "what", "needs"], steps=[
        {"do": "remember", "triples": [["{request_ref}", "failed_because", "{kind}"]]},
        {"when": {"is": ["{kind}", "not_understood"]}, "do": "say",
         "text": "I didn't understand “{what}”. Say “help” to see the kinds of thing I can do.", "and": "return"},
        {"when": {"is": ["{kind}", "cannot"]}, "do": "say",
         "text": "I understood “{what}”, but I can't do that: {needs}", "and": "return"},
        {"do": "say", "text": "I understood “{what}” and I could answer it, but I don't know yet: {needs}"},
    ]),

    # being told something, and asked about it
    Procedure(id="tell", act="tell", steps=[
        {"when": {"missing": "{slot.value}"}, "do": "call", "proc": "admit",
         "with": {"kind": "not_understood", "what": "{words}"}, "bind": {}},
        {"when": {"missing": "{slot.value}"}, "do": "stop"},
        {"do": "recall", "pattern": {"subject": "person:user", "predicate": "{slot.topic}"}, "as": "old"},
        {"do": "remember", "mode": "replace", "triples": [["person:user", "{slot.topic}", "{slot.value}"]]},
        {"when": {"truthy": "{old_any}"}, "do": "say",
         "text": "Noted — your {slot.topic} is {slot.value}. I had {old_objects|first} before; I've replaced it.", "and": "stop"},
        {"do": "say", "text": "Noted — your {slot.topic} is {slot.value}. Ask me any time."},
    ]),
    Procedure(id="ask_memory", act="ask_memory", steps=[
        {"do": "recall", "pattern": {"subject": "person:user"}, "as": "told"},
        {"do": "compute", "prim": "told_facts", "args": {"items": "{told_items}", "topic": "{slot.topic}"}},
        {"when": {"all": [{"exists": "{slot.topic}"}, {"exists": "{value}"}]}, "do": "compute", "prim": "shared_prefix",
         "args": {"subject": "person:user", "predicate": "{slot.topic}", "turn": "{turn}"}},
        {"when": {"all": [{"exists": "{slot.topic}"}, {"exists": "{value}"}, {"truthy": "{again}"}]}, "do": "say",
         "text": "{prefix}your {slot.topic} is {value} — you told me that ({told_in}).", "and": "stop"},
        {"when": {"all": [{"exists": "{slot.topic}"}, {"exists": "{value}"}]}, "do": "say",
         "text": "Your {slot.topic} is {value} — you told me that ({told_in}).", "and": "stop"},
        {"when": {"all": [{"exists": "{slot.topic}"}, {"truthy": "{n_facts}"}]}, "do": "call", "proc": "admit",
         "with": {"kind": "dont_know", "what": "{words}",
                  "needs": "you haven't told me your {slot.topic}. What you have told me: {topics|listing}."}, "bind": {}},
        {"when": {"all": [{"exists": "{slot.topic}"}, {"falsy": "{n_facts}"}]}, "do": "call", "proc": "admit",
         "with": {"kind": "dont_know", "what": "{words}", "needs": "you haven't told me anything about yourself yet."}, "bind": {}},
        {"when": {"exists": "{slot.topic}"}, "do": "stop"},
        {"when": {"falsy": "{n_facts}"}, "do": "say", "text": "You haven't told me anything about yourself yet.", "and": "stop"},
        {"do": "say", "text": "You've told me {n_facts} thing{n_facts|s}:\n{facts}"},
    ]),
    Procedure(id="forget", act="forget", steps=[
        {"do": "recall", "pattern": {"subject": "person:user"}, "as": "told"},
        {"when": {"falsy": "{told_any}"}, "do": "say", "text": "There's nothing I remember about you to forget.", "and": "stop"},
        {"when": {"missing": "{slot.topic}"}, "do": "remember", "mode": "forget", "triples": [["person:user", "*", ""]]},
        {"when": {"missing": "{slot.topic}"}, "do": "say", "text": "Forgotten — I've dropped all {told_n} thing{told_n|s} you told me.", "and": "stop"},
        {"do": "compute", "prim": "told_facts", "args": {"items": "{told_items}", "topic": "{slot.topic}"}},
        {"when": {"missing": "{value}"}, "do": "say", "text": "I don't have your {slot.topic} to forget.", "and": "stop"},
        {"do": "remember", "mode": "forget", "triples": [["person:user", "{slot.topic}", ""]]},
        {"do": "say", "text": "Forgotten — I no longer have your {slot.topic}."},
    ]),

    # what is on the screen: answered from what was perceived, not by running anything
    Procedure(id="ask_screen", act="ask_screen", steps=[
        {"do": "recall", "pattern": {"predicate": "label"}, "as": "ui", "limit": 400},
        {"do": "recall", "pattern": {"predicate": "reads"}, "as": "txt", "limit": 400},
        {"do": "compute", "prim": "screen_regions", "args": {"items": "{ui_items}", "texts": "{txt_items}"}},
        {"when": {"falsy": "{ui_any}"}, "do": "call", "proc": "admit",
         "with": {"kind": "dont_know", "what": "{words}", "needs": "I can't see the screen right now."}, "bind": {}},
        {"when": {"falsy": "{ui_any}"}, "do": "stop"},
        {"when": {"is": ["{slot.aspect}", "icons"]}, "do": "say",
         "text": "There are {dock_n} icons in the launcher strip on the left: {dock_items|listing}. (Seen on screen just now.)", "and": "stop"},
        {"when": {"is": ["{slot.aspect}", "windows"]}, "do": "say",
         "text": "{windows_n} window{windows_n|s} open: {windows|listing}.", "and": "stop"},
        {"when": {"is": ["{slot.aspect}", "window"]}, "do": "compute", "prim": "window_contents",
         "args": {"texts": "{txt_items}", "window": "{slot.window}"}},
        {"when": {"all": [{"is": ["{slot.aspect}", "window"]}, {"truthy": "{window_found}"}]}, "do": "say",
         "text": "The {window_name} window shows:\n{window_lines|lines}", "and": "stop"},
        {"when": {"is": ["{slot.aspect}", "window"]}, "do": "call", "proc": "admit",
         "with": {"kind": "dont_know", "what": "{words}",
                  "needs": "I can't see a “{slot.window}” window. Open now: {windows|listing}."}, "bind": {}},
        {"when": {"is": ["{slot.aspect}", "window"]}, "do": "stop"},
        {"when": {"is": ["{slot.aspect}", "is_open"]}, "do": "compute", "prim": "named_window",
         "args": {"windows": "{windows}", "window": "{slot.window}"}},
        {"when": {"all": [{"is": ["{slot.aspect}", "is_open"]}, {"truthy": "{window_is_open}"}]}, "do": "say",
         "text": "Yes — {matched_window} is open on screen.", "and": "stop"},
        {"when": {"is": ["{slot.aspect}", "is_open"]}, "do": "say",
         "text": "No — I can't see {slot.window}. What's open: {windows|listing}.", "and": "stop"},
        {"when": {"is": ["{slot.aspect}", "changed"]}, "do": "changes", "since": "last_message", "as": "chg"},
        {"when": {"all": [{"is": ["{slot.aspect}", "changed"]}, {"exists": "{chg_unavailable}"}]}, "do": "call", "proc": "admit",
         "with": {"kind": "dont_know", "what": "{words}", "needs": "{chg_unavailable}"}, "bind": {}},
        {"when": {"all": [{"is": ["{slot.aspect}", "changed"]}, {"exists": "{chg_unavailable}"}]}, "do": "stop"},
        {"when": {"all": [{"is": ["{slot.aspect}", "changed"]}, {"falsy": "{chg_any}"}]}, "do": "say",
         "text": "Nothing changed on screen since your last message (I ignored {chg_volatile_n} thing{chg_volatile_n|s} that change on their own, like the clock).", "and": "stop"},
        {"when": {"is": ["{slot.aspect}", "changed"]}, "do": "say",
         "text": "{chg_n} thing{chg_n|s} changed since your last message:\n{chg_lines|lines}", "and": "stop"},
        {"do": "say", "text": "On screen: {windows_n} window{windows_n|s} ({windows|listing}), a launcher of {dock_n} icons ({dock_items|listing}), and {controls_n} things I can click."},
    ]),

    # how it looks: this one needs pixels, a modality the accessible structure cannot answer
    Procedure(id="ask_pixels", act="ask_pixels", steps=[
        {"do": "sample", "region": "{slot.region}", "as": "px"},
        {"do": "compute", "prim": "color_words", "args": {"colors": "{px_colors}", "unavailable": "{px_unavailable}"}},
        {"when": {"exists": "{unavailable}"}, "do": "call", "proc": "admit",
         "with": {"kind": "cannot", "what": "{words}", "needs": "{unavailable}."}, "bind": {}},
        {"when": {"exists": "{unavailable}"}, "do": "stop"},
        {"when": {"missing": "{main_color}"}, "do": "call", "proc": "admit",
         "with": {"kind": "dont_know", "what": "{words}", "needs": "I sampled {slot.region} but got no pixels back."}, "bind": {}},
        {"when": {"missing": "{main_color}"}, "do": "stop"},
        {"do": "say", "text": "I looked at the pixels of the {slot.region}: mostly {main_color}. The mix is {palette}."},
    ]),

    # what I did, and why: read off my own commands and the procedure that asked for them
    Procedure(id="ask_self", act="ask_self", steps=[
        {"when": {"is": ["{slot.aspect}", "history"]}, "do": "recall",
         "pattern": {"predicate": "text", "subject_prefix": "utterance:"}, "as": "said", "limit": 60},
        {"when": {"is": ["{slot.aspect}", "history"]}, "do": "compute", "prim": "own_actions",
         "args": {"items": "{said_items}", "limit": 8}, "as": "asked"},
        {"when": {"all": [{"is": ["{slot.aspect}", "history"]}, {"falsy": "{asked_n_actions}"}]}, "do": "say",
         "text": "You haven't asked me anything yet.", "and": "stop"},
        {"when": {"is": ["{slot.aspect}", "history"]}, "do": "say",
         "text": "You've asked me:\n{asked_actions|lines}", "and": "stop"},
        {"do": "recall", "pattern": {"predicate": "why"}, "as": "acts", "limit": 200},
        {"do": "compute", "prim": "own_actions", "args": {"items": "{acts_items}"}},
        {"when": {"falsy": "{n_actions}"}, "do": "say", "text": "I haven't done anything yet — you haven't asked me to.", "and": "stop"},
        # why: walk from the action back to the request that asked for it, not to whatever I am doing now
        {"when": {"is": ["{slot.aspect}", "why"]}, "do": "recall",
         "pattern": {"subject": "{last_subject}", "predicate": "for"}, "as": "owner"},
        {"when": {"is": ["{slot.aspect}", "why"]}, "do": "recall",
         "pattern": {"subject": "{owner_objects|first}", "predicate": "words"}, "as": "asked"},
        {"when": {"all": [{"is": ["{slot.aspect}", "why"]}, {"truthy": "{asked_any}"}]}, "do": "say",
         "text": "I did “{last_action}” because you asked me to “{asked_objects|first}”. Which step it came from is in my notes.", "and": "stop"},
        {"when": {"is": ["{slot.aspect}", "why"]}, "do": "say",
         "text": "I did “{last_action}”, but I can't trace which request asked for it.", "and": "stop"},
        {"when": {"is": ["{slot.aspect}", "last_action"]}, "do": "say", "text": "Just now I did: {last_action}.", "and": "stop"},
        {"do": "say", "text": "The last {phrase} I did:\n{actions|lines}"},
    ]),

    # an app named by what it is for, which crosses prior knowledge -> the screen -> an action
    Procedure(id="open_function", act="open_function", steps=[
        {"do": "recall", "pattern": {"predicate": "is_for"}, "as": "fn", "limit": 400},
        {"do": "compute", "prim": "match_function", "args": {"items": "{fn_items}", "phrase": "{slot.function}"}},
        {"do": "recall", "pattern": {"predicate": "label"}, "as": "ui", "limit": 400},
        {"do": "compute", "prim": "screen_regions", "args": {"items": "{ui_items}"}},
        {"when": {"truthy": "{ambiguous}"}, "do": "say",
         "text": "More than one app fits “{slot.function}”: {candidates|listing}. Which one?", "and": "stop"},
        {"when": {"missing": "{app}"}, "do": "call", "proc": "admit",
         "with": {"kind": "dont_know", "what": "{words}",
                  "needs": "I don't know which app is for that. I can see these in the launcher: {dock_items|listing}."}, "bind": {}},
        {"when": {"missing": "{app}"}, "do": "stop"},
        {"when": {"truthy": "{slot.ask_only}"}, "do": "say",
         "text": "{app} — that's the one for {slot.function}. Say “open {app}” and I will.", "and": "stop"},
        {"do": "open_app", "app": "{app}"},
        {"when": {"truthy": "{opened}"}, "do": "say", "text": "Opened {app}, which is the app for {slot.function}.", "and": "stop"},
        {"do": "call", "proc": "admit",
         "with": {"kind": "cannot", "what": "{words}",
                  "needs": "{app} is the app for that, but I clicked it and no window appeared."}, "bind": {}},
    ]),

    # ------------------------------------------------------- making things
    Procedure(id="create_folder", act="create_folder", steps=[
        {"when": {"missing": "{slot.name}"}, "do": "say", "text": "What should I call the folder?", "and": "stop"},
        {"do": "call", "proc": "folder_for_new", "with": {"place": "{slot.place}"}, "bind": {"place": "place"}},
        {"when": {"missing": "{place}"}, "do": "stop"},
        {"do": "compute", "prim": "expand", "args": {"path": "{slot.name}", "cwd": "{place}"}},
        {"do": "run", "command": STAT, "why": "check {path|show} first", "as": "before"},
        {"do": "compute", "prim": "stat_map", "args": {"out": "{before_out}"}},
        {"do": "compute", "prim": "kind_of", "args": {"stats": "{stats}", "path": "{path}"}},
        {"when": {"exists": "{kind}"}, "do": "focus", "path": "{path}", "kind": "{kind}"},
        {"when": {"is": ["{kind}", "directory"]}, "do": "say", "text": "There's already a folder at {path|show}, so I left it alone.", "and": "stop"},
        {"when": {"exists": "{kind}"}, "do": "say", "text": "There's already a file at {path|show}, so I left it alone.", "and": "stop"},
        {"do": "run", "command": "mkdir -p {path|q}", "why": "create {path|show}"},
        {"do": "run", "command": STAT, "why": "check {path|show} is there", "as": "after"},
        {"do": "compute", "prim": "stat_map", "args": {"out": "{after_out}"}, "as": "post"},
        {"do": "compute", "prim": "kind_of", "args": {"stats": "{post_stats}", "path": "{path}"}, "as": "now"},
        {"when": {"is": ["{now_kind}", "directory"]}, "do": "focus", "path": "{path}", "kind": "directory"},
        {"when": {"is": ["{now_kind}", "directory"]}, "do": "say", "text": "Created the folder {path|show}.", "and": "stop"},
        {"do": "say", "text": "I tried to create {path|show} but it isn't there: {error_summary}"},
    ]),
    Procedure(id="folder_for_new", takes=["place"], returns=["place"], steps=[
        {"do": "compute", "prim": "place_for_new", "args": {"place": "{place}", "focus": "{focus}", "focus_kind": "{focus_kind}", "cwd": "{cwd}"}, "as": "pick"},
        {"when": {"falsy": "{pick_needs_resolving}"}, "do": "return", "values": {"place": "{pick_place}"}},
        {"do": "call", "proc": "resolve", "with": {"ref": "{pick_place}", "want": "directory", "what": "folder"}, "bind": {"found": "path"}},
        {"do": "return", "values": {"place": "{found}"}},
    ]),
    Procedure(id="create_file", act="create_file", steps=[
        {"when": {"missing": "{slot.name}"}, "do": "say", "text": "What should I call the file?", "and": "stop"},
        {"do": "call", "proc": "folder_for_new", "with": {"place": "{slot.place}"}, "bind": {"place": "place"}},
        {"when": {"missing": "{place}"}, "do": "stop"},
        {"do": "compute", "prim": "expand", "args": {"path": "{slot.name}", "cwd": "{place}"}},
        {"do": "run", "command": "stat -c '%F|%s|%n' {path|q} {path|parent|q}", "why": "check {path|show} first", "as": "before"},
        {"do": "compute", "prim": "stat_map", "args": {"out": "{before_out}"}},
        {"do": "compute", "prim": "kind_of", "args": {"stats": "{stats}", "path": "{path|parent}"}, "as": "folder"},
        {"when": {"missing": "{folder_kind}"}, "do": "say",
         "text": "The folder {path|parent|show} doesn't exist. Want me to create it first? Say “make a folder called {path|parent|base} in {path|parent|parent|show}”.", "and": "stop"},
        {"do": "compute", "prim": "kind_of", "args": {"stats": "{stats}", "path": "{path}"}},
        {"when": {"all": [{"exists": "{kind}"}, {"missing": "{slot.text}"}]}, "do": "focus", "path": "{path}", "kind": "{kind}"},
        {"when": {"all": [{"exists": "{kind}"}, {"missing": "{slot.text}"}]}, "do": "say",
         "text": "{path|show} already exists, so I left it alone.", "and": "stop"},
        {"when": {"exists": "{slot.text}"}, "do": "run", "command": "printf '%s\\n' {slot.text|q} > {path|q}", "why": "write {path|show}", "as": "write"},
        {"when": {"missing": "{slot.text}"}, "do": "run", "command": "touch {path|q}", "why": "create {path|show}", "as": "write"},
        {"when": {"exists": "{kind}"}, "do": "call", "proc": "verify_file",
         "with": {"path": "{path}", "text": "{slot.text}", "verb": "Replaced the contents of", "write_ok": "{write_ok}", "write_error": "{write_error_summary}"}, "bind": {}},
        {"when": {"exists": "{kind}"}, "do": "stop"},
        {"do": "call", "proc": "verify_file",
         "with": {"path": "{path}", "text": "{slot.text}", "verb": "Created", "write_ok": "{write_ok}", "write_error": "{write_error_summary}"}, "bind": {}},
    ]),
    Procedure(id="write", act="write", steps=[
        {"do": "call", "proc": "writable_path", "with": {"target": "{slot.target}"}, "bind": {"path": "path"}},
        {"when": {"missing": "{path}"}, "do": "stop"},
        {"do": "run", "command": STAT, "why": "check {path|show} first", "as": "before"},
        {"do": "compute", "prim": "stat_map", "args": {"out": "{before_out}"}},
        {"do": "compute", "prim": "kind_of", "args": {"stats": "{stats}", "path": "{path}"}},
        {"when": {"is": ["{kind}", "directory"]}, "do": "say", "text": "{path|show} is a folder, not a file.", "and": "stop"},
        {"do": "compute", "prim": "text_or", "args": {"value": "{slot.text}", "fallback": ""}, "as": "body"},
        {"when": {"truthy": "{slot.append}"}, "do": "run", "command": "printf '%s\\n' {body_text|q} >> {path|q}", "why": "append to {path|show}", "as": "write"},
        {"when": {"falsy": "{slot.append}"}, "do": "run", "command": "printf '%s\\n' {body_text|q} > {path|q}", "why": "write {path|show}", "as": "write"},
        {"when": {"truthy": "{slot.append}"}, "do": "call", "proc": "verify_file",
         "with": {"path": "{path}", "text": "{body_text}", "verb": "Added a line to", "write_ok": "{write_ok}", "write_error": "{write_error_summary}"}, "bind": {}},
        {"when": {"truthy": "{slot.append}"}, "do": "stop"},
        {"do": "call", "proc": "verify_file",
         "with": {"path": "{path}", "text": "{body_text}", "verb": "Wrote", "write_ok": "{write_ok}", "write_error": "{write_error_summary}"}, "bind": {}},
    ]),
    Procedure(id="writable_path", takes=["target"], returns=["path"], steps=[
        # a filename that does not exist yet is still writable: look where the conversation is before searching
        {"do": "compute", "prim": "new_file_guess", "args": {"target": "{target}", "focus": "{focus}", "focus_kind": "{focus_kind}", "cwd": "{cwd}", "known": "{known}"}},
        {"when": {"falsy": "{guessable}"}, "do": "call", "proc": "resolve",
         "with": {"ref": "{target}", "want": "regular file", "what": "file"}, "bind": {"found": "path"}},
        {"when": {"falsy": "{guessable}"}, "do": "return", "values": {"path": "{found}"}},
        {"when": {"exists": "{known_path}"}, "do": "return", "values": {"path": "{known_path}"}},
        {"do": "run", "command": "stat -c '%F|%s|%n' {guess|q}", "why": "check {guess|show}", "as": "here"},
        {"do": "compute", "prim": "stat_map", "args": {"out": "{here_out}"}},
        {"do": "compute", "prim": "kind_of", "args": {"stats": "{stats}", "path": "{guess}"}},
        {"when": {"exists": "{kind}"}, "do": "return", "values": {"path": "{guess}"}},
        {"do": "call", "proc": "resolve", "with": {"ref": "{target}", "want": "regular file", "what": "file"}, "bind": {"found": "path"}},
        {"do": "return", "values": {"path": "{found}"}},
    ]),
    Procedure(id="verify_file", takes=["path", "text", "verb", "write_ok", "write_error"], steps=[
        {"do": "run", "command": "tail -n 3 {path|q}", "why": "read {path|show} back", "as": "check"},
        {"when": {"falsy": "{write_ok}"}, "do": "say", "text": "Something went wrong with {path|show}: {write_error}", "and": "return"},
        {"when": {"falsy": "{check_ok}"}, "do": "say", "text": "Something went wrong with {path|show}: {check_error_summary}", "and": "return"},
        {"do": "compute", "prim": "contains_text", "args": {"haystack": "{check_out}", "needle": "{text}"}},
        {"when": {"all": [{"exists": "{text}"}, {"falsy": "{found}"}]}, "do": "say",
         "text": "I wrote to {path|show}, but reading it back I don't see “{text}”. It ends with:\n{check_out|trim}", "and": "return"},
        {"do": "focus", "path": "{path}", "kind": "regular file"},
        {"do": "compute", "prim": "suffix_note", "args": {"text": "{text}"}},
        {"do": "say", "text": "{verb} {path|show}.{tail}"},
    ]),

    # ---------------------------------------------------- changing things
    Procedure(id="delete", act="delete", steps=[
        {"do": "call", "proc": "resolve", "with": {"ref": "{slot.target}", "what": "file or folder"}, "bind": {"path": "path"}},
        {"when": {"missing": "{path}"}, "do": "stop"},
        {"do": "run", "command": STAT, "why": "look at {path|show}", "as": "before"},
        {"do": "compute", "prim": "stat_map", "args": {"out": "{before_out}"}},
        {"do": "compute", "prim": "kind_of", "args": {"stats": "{stats}", "path": "{path}"}},
        {"when": {"missing": "{kind}"}, "do": "say", "text": "There's no {path|show} to delete.", "and": "stop"},
        {"do": "compute", "prim": "wants_everything", "args": {"words": "{words}"}},
        {"when": {"all": [{"truthy": "{everything}"}, {"is": ["{kind}", "directory"]}]},
         "do": "call", "proc": "empty_folder", "with": {"path": "{path}"}, "bind": {}},
        {"when": {"all": [{"truthy": "{everything}"}, {"is": ["{kind}", "directory"]}]}, "do": "stop"},
        {"when": {"is": ["{kind}", "directory"]}, "do": "run", "command": "ls -1pA {path|q}", "why": "see what is in {path|show}", "as": "inside"},
        {"when": {"is": ["{kind}", "directory"]}, "do": "compute", "prim": "ls_facts", "args": {"out": "{inside_out}"}, "as": "in"},
        {"do": "compute", "prim": "contents_note", "args": {"kind": "{kind}", "n": "{in_n_names}"}},
        {"do": "compute", "prim": "rm_flag", "args": {"kind": "{kind}"}},
        {"do": "run", "command": "rm {rm}{path|q}", "why": "delete {path|show}{contents}"},
        {"do": "run", "command": STAT, "why": "check {path|show} is gone", "as": "after"},
        {"do": "compute", "prim": "stat_map", "args": {"out": "{after_out}"}, "as": "post"},
        {"do": "compute", "prim": "kind_of", "args": {"stats": "{post_stats}", "path": "{path}"}, "as": "now"},
        {"when": {"missing": "{now_kind}"}, "do": "say", "text": "Deleted {path|show}.", "and": "stop"},
        {"do": "say", "text": "I couldn't delete {path|show}: {error_summary}"},
    ]),
    Procedure(id="empty_folder", takes=["path"], steps=[
        {"do": "run", "command": "ls -1pA {path|q}", "why": "see what is in {path|show}"},
        {"do": "compute", "prim": "ls_facts", "args": {"out": "{out}"}},
        {"when": {"falsy": "{names}"}, "do": "say", "text": "{path|show} is already empty.", "and": "return"},
        {"do": "compute", "prim": "rm_all_command", "args": {"path": "{path}", "names": "{names}"}},
        {"do": "run", "command": "{command}", "why": "empty {path|show}", "as": "rm"},
        {"do": "run", "command": "ls -1pA {path|q}", "why": "check {path|show} is empty", "as": "after"},
        {"do": "compute", "prim": "ls_facts", "args": {"out": "{after_out}"}, "as": "left"},
        {"do": "compute", "prim": "deleted_note", "args": {"before": "{n_names}", "after": "{left_n_names}", "names": "{left_names}"}},
        {"do": "say", "text": "Deleted {deleted} items from {path|show}.{still}"},
    ]),
    Procedure(id="move", act="move", steps=[{"do": "call", "proc": "move_or_copy", "with": {}, "bind": {}}]),
    Procedure(id="copy", act="copy", steps=[{"do": "call", "proc": "move_or_copy", "with": {}, "bind": {}}]),
    Procedure(id="move_or_copy", steps=[
        {"do": "compute", "prim": "is_copy", "args": {"act": "{act}"}},
        {"do": "call", "proc": "resolve", "with": {"ref": "{slot.target}", "what": "file or folder"}, "bind": {"src": "path"}},
        {"when": {"missing": "{src}"}, "do": "stop"},
        {"do": "call", "proc": "resolve", "with": {"ref": "{slot.dest}", "want": "directory", "what": "destination folder"}, "bind": {"dest_dir": "path"}},
        {"when": {"missing": "{dest_dir}"}, "do": "stop"},
        {"do": "compute", "prim": "join_path", "args": {"folder": "{dest_dir}", "name": "{src}"}, "as": "to"},
        {"do": "run", "command": "stat -c '%F|%s|%n' {src|q} {to_path|q}", "why": "look at both ends", "as": "before"},
        {"do": "compute", "prim": "stat_map", "args": {"out": "{before_out}"}},
        {"do": "compute", "prim": "kind_of", "args": {"stats": "{stats}", "path": "{src}"}, "as": "from"},
        {"do": "compute", "prim": "kind_of", "args": {"stats": "{stats}", "path": "{to_path}"}, "as": "dest"},
        {"when": {"missing": "{from_kind}"}, "do": "say", "text": "There's no {src|show}.", "and": "stop"},
        {"do": "compute", "prim": "copy_command", "args": {"copy": "{copy}", "kind": "{from_kind}"}},
        {"when": {"exists": "{dest_kind}"}, "do": "say", "text": "{to_path|show} already exists, so I didn't {verbing} anything.", "and": "stop"},
        {"do": "run", "command": "{cmd} {src|q} {to_path|q}", "why": "{verbing} {src|show} to {dest_dir|show}"},
        {"do": "run", "command": "stat -c '%F|%s|%n' {src|q} {to_path|q}", "why": "check both ends", "as": "after"},
        {"do": "compute", "prim": "stat_map", "args": {"out": "{after_out}"}, "as": "post"},
        {"do": "compute", "prim": "kind_of", "args": {"stats": "{post_stats}", "path": "{to_path}"}, "as": "landed"},
        {"do": "compute", "prim": "kind_of", "args": {"stats": "{post_stats}", "path": "{src}"}, "as": "origin"},
        {"when": {"missing": "{landed_kind}"}, "do": "say", "text": "That didn't work: {error_summary}", "and": "stop"},
        {"when": {"all": [{"falsy": "{copy}"}, {"exists": "{origin_kind}"}]}, "do": "say", "text": "That didn't work: {error_summary}", "and": "stop"},
        {"do": "focus", "path": "{to_path}", "kind": "{from_kind}"},
        {"do": "say", "text": "{verb} {src|show} to {to_path|show}."},
    ]),
    Procedure(id="rename", act="rename", steps=[
        {"do": "call", "proc": "resolve", "with": {"ref": "{slot.target}", "what": "file or folder"}, "bind": {"src": "path"}},
        {"when": {"missing": "{src}"}, "do": "stop"},
        {"do": "compute", "prim": "new_name_ok", "args": {"new_name": "{slot.new_name}"}},
        {"when": {"falsy": "{usable}"}, "do": "say", "text": "What should the new name be? (Just a name, like ideas.txt.)", "and": "stop"},
        {"do": "compute", "prim": "join_path", "args": {"folder": "{src|parent}", "name": "{new_name}"}, "as": "to"},
        {"do": "run", "command": "stat -c '%F|%s|%n' {src|q} {to_path|q}", "why": "look at both names", "as": "before"},
        {"do": "compute", "prim": "stat_map", "args": {"out": "{before_out}"}},
        {"do": "compute", "prim": "kind_of", "args": {"stats": "{stats}", "path": "{src}"}, "as": "from"},
        {"do": "compute", "prim": "kind_of", "args": {"stats": "{stats}", "path": "{to_path}"}, "as": "dest"},
        {"when": {"missing": "{from_kind}"}, "do": "say", "text": "There's no {src|show}.", "and": "stop"},
        {"when": {"exists": "{dest_kind}"}, "do": "say", "text": "{to_path|show} already exists, so I didn't rename anything.", "and": "stop"},
        {"do": "run", "command": "mv {src|q} {to_path|q}", "why": "rename {src|base} to {new_name}"},
        {"do": "run", "command": "stat -c '%F|%s|%n' {src|q} {to_path|q}", "why": "check the new name", "as": "after"},
        {"do": "compute", "prim": "stat_map", "args": {"out": "{after_out}"}, "as": "post"},
        {"do": "compute", "prim": "kind_of", "args": {"stats": "{post_stats}", "path": "{to_path}"}, "as": "landed"},
        {"do": "compute", "prim": "kind_of", "args": {"stats": "{post_stats}", "path": "{src}"}, "as": "origin"},
        {"when": {"any": [{"missing": "{landed_kind}"}, {"exists": "{origin_kind}"}]}, "do": "say", "text": "That didn't work: {error_summary}", "and": "stop"},
        {"do": "focus", "path": "{to_path}", "kind": "{from_kind}"},
        {"do": "say", "text": "Renamed {src|show} to {new_name}."},
    ]),

    # --------------------------------------------------------- searching
    Procedure(id="find", act="find", steps=[
        {"do": "compute", "prim": "text_or", "args": {"value": "{slot.place}", "fallback": "~"}, "as": "where"},
        {"do": "compute", "prim": "text_or", "args": {"value": "{slot.pattern}", "fallback": "*"}, "as": "pat"},
        {"do": "call", "proc": "resolve", "with": {"ref": "{where_text}", "want": "directory", "what": "folder"}, "bind": {"root": "path"}},
        {"when": {"missing": "{root}"}, "do": "stop"},
        {"do": "run", "command": "find {root|q} -name {pat_text|q} 2>/dev/null | head -n 60", "why": "search {root|show} for {pat_text}"},
        {"do": "compute", "prim": "paths_in_output", "args": {"out": "{out}", "limit": 60}},
        {"when": {"falsy": "{hits}"}, "do": "say", "text": "Nothing matching “{pat_text}” in {root|show}.", "and": "stop"},
        {"when": {"eq": ["{n_hits}", 1]}, "do": "focus", "path": "{hits.0}", "kind": "regular file"},
        {"do": "compute", "prim": "shown_paths", "args": {"paths": "{hits}"}},
        {"do": "say", "text": "Found {n_hits} matching “{pat_text}” in {root|show}: {shown|listing:15}"},
    ]),
    Procedure(id="grep", act="grep", steps=[
        {"do": "compute", "prim": "text_or", "args": {"value": "{slot.place}", "fallback": "~"}, "as": "where"},
        {"do": "call", "proc": "resolve", "with": {"ref": "{where_text}", "what": "folder"}, "bind": {"root": "path"}},
        {"when": {"missing": "{root}"}, "do": "stop"},
        {"do": "run", "command": "grep -ril {slot.needle|q} {root|q} 2>/dev/null | head -n 80", "why": "search inside files for “{slot.needle}”"},
        {"do": "compute", "prim": "paths_in_output", "args": {"out": "{out}", "limit": 80}},
        {"when": {"falsy": "{hits}"}, "do": "say", "text": "No files in {root|show} mention “{slot.needle}”.", "and": "stop"},
        {"when": {"eq": ["{n_hits}", 1]}, "do": "focus", "path": "{hits.0}", "kind": "regular file"},
        {"do": "compute", "prim": "shown_paths", "args": {"paths": "{hits}"}},
        {"do": "say", "text": "{n_hits} file{n_hits|s} in {root|show} mention{n_hits|verb_s} “{slot.needle}”: {shown|listing:15}"},
    ]),
    Procedure(id="count", act="count", steps=[
        {"do": "call", "proc": "resolve", "with": {"ref": "{slot.target}", "want": "regular file", "what": "file"}, "bind": {"path": "path"}},
        {"when": {"missing": "{path}"}, "do": "stop"},
        {"do": "compute", "prim": "text_or", "args": {"value": "{slot.unit}", "fallback": "lines"}, "as": "u"},
        {"do": "compute", "prim": "wc_flag", "args": {"unit": "{u_text}"}},
        {"do": "run", "command": "wc -{flag} < {path|q}", "why": "count {u_text} in {path|show}"},
        {"do": "compute", "prim": "first_number", "args": {"lines": "{lines}"}},
        {"do": "focus", "path": "{path}", "kind": "regular file"},
        {"when": {"missing": "{number}"}, "do": "say", "text": "I couldn't count: {error_summary}", "and": "stop"},
        {"do": "compute", "prim": "plural_words", "args": {"n": "{number}", "unit": "{u_text}"}},
        {"do": "say", "text": "{path|show} has {number} {unit}."},
    ]),
    Procedure(id="size", act="size", steps=[
        {"do": "call", "proc": "resolve", "with": {"ref": "{slot.target}", "what": "file or folder"}, "bind": {"path": "path"}},
        {"when": {"missing": "{path}"}, "do": "stop"},
        {"do": "run", "command": "du -sh {path|q}", "why": "measure {path|show}"},
        {"do": "compute", "prim": "first_field", "args": {"lines": "{lines}"}},
        {"when": {"all": [{"exists": "{field}"}, {"truthy": "{ok}"}]}, "do": "say", "text": "{path|show} takes up {field}.", "and": "stop"},
        {"do": "say", "text": "I couldn't measure {path|show}: {error_summary}"},
    ]),

    # ------------------------------------------------------- the machine
    Procedure(id="info", act="info", steps=[
        {"do": "compute", "prim": "info_command", "args": {"topic": "{slot.topic}"}},
        {"do": "run", "command": "{command}", "why": "check {slot.topic}"},
        {"when": {"truthy": "{ok}"}, "do": "compute", "prim": "info_reply", "args": {"topic": "{slot.topic}", "out": "{out}", "lines": "{lines}"}},
        {"when": {"exists": "{reply}"}, "do": "say", "text": "{reply}", "and": "stop"},
        {"do": "say", "text": "I ran `{command}` but couldn't make sense of the result: {error_summary}"},
    ]),
    Procedure(id="which", act="which", steps=[
        {"do": "run", "command": "which {slot.program|q}", "why": "look for {slot.program}"},
        {"do": "compute", "prim": "first_path", "args": {"lines": "{lines}"}},
        {"when": {"exists": "{path_found}"}, "do": "say", "text": "Yes, {slot.program} is installed at {path_found}.", "and": "stop"},
        {"do": "say", "text": "No, {slot.program} isn't installed (or isn't on the PATH)."},
    ]),
    Procedure(id="cd", act="cd", steps=[
        {"do": "call", "proc": "resolve", "with": {"ref": "{slot.target}", "want": "directory", "what": "folder"}, "bind": {"path": "path"}},
        {"when": {"missing": "{path}"}, "do": "stop"},
        {"do": "run", "command": "cd {path|q}", "why": "go to {path|show}"},
        {"when": {"falsy": "{ok}"}, "do": "say", "text": "I couldn't go there: {error_summary}", "and": "stop"},
        {"do": "focus", "path": "{path}", "kind": "directory"},
        {"do": "say", "text": "Now working in {path|show}."},
    ]),
    Procedure(id="open_app", act="open_app", steps=[
        {"do": "open_app", "app": "{slot.app}"},
        {"when": {"truthy": "{opened}"}, "do": "say", "text": "Opened {slot.app}.", "and": "stop"},
        {"do": "say", "text": "I clicked {slot.app} in the dock, but I don't see its window."},
    ]),
    Procedure(id="run", act="run", steps=[
        {"do": "run", "command": "{slot.command}", "why": "run your command"},
        {"when": {"truthy": "{timed_out}"}, "do": "say",
         "text": "`{slot.command}` is still running after a while; I stopped waiting. So far:\n{out|tail:1500}", "and": "stop"},
        {"when": {"falsy": "{out|trim}"}, "do": "say", "text": "Ran `{slot.command}` (no output).", "and": "stop"},
        {"do": "say", "text": "Ran `{slot.command}`:\n{out|trim|tail:2500}"},
    ]),
    Procedure(id="install", act="install", steps=[
        {"do": "run", "command": "sudo apt install -y {slot.package|q}", "why": "install {slot.package}"},
        {"when": {"falsy": "{ok}"}, "do": "say", "text": "apt said: {error_summary}", "and": "stop"},
        {"when": {"truthy": "{lines}"}, "do": "say", "text": "Installed {slot.package}.", "and": "stop"},
        {"do": "say", "text": "apt finished without output."},
    ]),

    # --------------------------------------------- a whole project at once
    Procedure(id="setup_project", act="setup_project", steps=[
        {"do": "compute", "prim": "project_note", "args": {"note": "{slot.note}"}},
        {"when": {"falsy": "{readable}"}, "do": "say",
         "text": "I couldn't read that as a project setup ({why}). Try: “set up a project called demo under ~/Projects. README.md should say 'Demo'. todo: first; second. commit with message 'init'”.", "and": "stop"},
        {"do": "compute", "prim": "next_command", "args": {"commands": "{commands}", "index": 0, "step_ids": "{step_ids}"}},
        {"do": "call", "proc": "project_step", "with": {"commands": "{commands}", "step_ids": "{step_ids}", "index": "{next_index}",
                                                        "command": "{command}", "step_id": "{step_id}", "last": "{last}",
                                                        "title": "{title}", "message": "{message}", "root": "{root}", "n_items": "{n_items}"}, "bind": {}},
    ]),
    Procedure(id="project_step", takes=["commands", "step_ids", "index", "command", "step_id", "last", "title", "message", "root", "n_items"], steps=[
        {"do": "run", "command": "{command}", "why": "step {step_id}"},
        {"do": "compute", "prim": "contains_text", "args": {"haystack": "{out}", "needle": "nothing to commit"}, "as": "benign"},
        {"when": {"all": [{"falsy": "{ok}"}, {"falsy": "{benign_found}"}]}, "do": "say",
         "text": "Step “{step_id}” failed: {error_summary}. I stopped there.", "and": "stop"},
        {"when": {"truthy": "{last}"}, "do": "compute", "prim": "project_verified", "args": {"out": "{out}", "title": "{title}", "message": "{message}"}},
        {"when": {"truthy": "{last}"}, "do": "focus", "path": "{root}", "kind": "directory"},
        {"when": {"all": [{"truthy": "{last}"}, {"truthy": "{verified}"}]}, "do": "say",
         "text": "Set up {root|show} with README, notes/todo.txt ({n_items} items) and a commit “{message}”.", "and": "stop"},
        {"when": {"truthy": "{last}"}, "do": "say",
         "text": "I ran every step, but reading back {root|show} didn't show what I expected:\n{out|head_lines:12}", "and": "stop"},
        {"do": "compute", "prim": "next_command", "args": {"commands": "{commands}", "index": "{index}", "step_ids": "{step_ids}"}},
        {"do": "call", "proc": "project_step", "with": {"commands": "{commands}", "step_ids": "{step_ids}", "index": "{next_index}",
                                                        "command": "{command}", "step_id": "{step_id}", "last": "{last}",
                                                        "title": "{title}", "message": "{message}", "root": "{root}", "n_items": "{n_items}"}, "bind": {}},
    ]),

    # ------------------------------------------------------------- git
    Procedure(id="git_init", act="git_init", steps=[
        {"do": "call", "proc": "resolve", "with": {"ref": "{slot.target}", "want": "directory", "what": "folder"}, "bind": {"path": "path"}},
        {"when": {"missing": "{path}"}, "do": "stop"},
        {"do": "run", "command": "stat -c '%F|%s|%n' {path|q}/.git", "why": "check {path|show} for a repository", "as": "before"},
        {"do": "compute", "prim": "contains_text", "args": {"haystack": "{before_out}", "needle": "directory|"}, "as": "repo"},
        {"when": {"truthy": "{repo_found}"}, "do": "focus", "path": "{path}", "kind": "directory"},
        {"when": {"truthy": "{repo_found}"}, "do": "say", "text": "{path|show} is already a git repository.", "and": "stop"},
        {"do": "run", "command": "git -C {path|q} init", "why": "make {path|show} a repository"},
        {"do": "focus", "path": "{path}", "kind": "directory"},
        {"do": "compute", "prim": "contains_text", "args": {"haystack": "{out}", "needle": "Reinitialized"}, "as": "again"},
        {"when": {"truthy": "{again_found}"}, "do": "say",
         "text": "{path|show} was already a git repository (git re-initialized it, nothing was lost).", "and": "stop"},
        {"do": "compute", "prim": "contains_text", "args": {"haystack": "{out}", "needle": "Initialized"}},
        {"when": {"truthy": "{found}"}, "do": "say", "text": "{path|show} is now a git repository.", "and": "stop"},
        {"do": "say", "text": "git init failed: {error_summary}"},
    ]),
    Procedure(id="git_commit", act="git_commit", steps=[
        {"do": "call", "proc": "resolve", "with": {"ref": "{slot.target}", "want": "directory", "what": "folder"}, "bind": {"path": "path"}},
        {"when": {"missing": "{path}"}, "do": "stop"},
        {"when": {"missing": "{slot.message}"}, "do": "say",
         "text": "What commit message should I use? Say something like “commit everything in {path|base} as 'first draft'”.", "and": "stop"},
        {"do": "run", "command": "git -C {path|q} status --short", "why": "see what changed in {path|show}", "as": "status"},
        {"do": "compute", "prim": "contains_text", "args": {"haystack": "{status_out}", "needle": "not a git"}, "as": "norepo"},
        {"when": {"truthy": "{norepo_found}"}, "do": "say",
         "text": "{path|show} isn't a git repository yet. Say “make {path|base} a git repo” first.", "and": "stop"},
        {"when": {"falsy": "{status_ok}"}, "do": "say", "text": "git status failed: {status_error_summary}", "and": "stop"},
        {"when": {"falsy": "{status_lines}"}, "do": "say", "text": "Nothing to commit in {path|show}; everything is already committed.", "and": "stop"},
        {"do": "run", "command": "git -C {path|q} add -A && git -C {path|q} commit -m {slot.message|q}", "why": "commit {status_lines|count} changes"},
        {"do": "run", "command": "git -C {path|q} log --oneline -n 1", "why": "check the commit", "as": "log"},
        {"do": "focus", "path": "{path}", "kind": "directory"},
        {"do": "compute", "prim": "git_message", "args": {"text": "{log_out}", "message": "{slot.message}"}},
        {"when": {"truthy": "{in_log}"}, "do": "say",
         "text": "Committed {status_lines|count} change{status_lines|count|s} in {path|show}: {log_lines|first}", "and": "stop"},
        {"do": "say", "text": "The commit didn't show up in the log: {error_summary}"},
    ]),
    Procedure(id="git_status", act="git_status", steps=[
        {"do": "call", "proc": "resolve", "with": {"ref": "{slot.target}", "want": "directory", "what": "folder"}, "bind": {"path": "path"}},
        {"when": {"missing": "{path}"}, "do": "stop"},
        {"do": "run", "command": "git -C {path|q} status --short", "why": "git status in {path|show}"},
        {"do": "focus", "path": "{path}", "kind": "directory"},
        {"do": "compute", "prim": "contains_text", "args": {"haystack": "{out}", "needle": "not a git"}, "as": "norepo"},
        {"when": {"truthy": "{norepo_found}"}, "do": "say", "text": "{path|show} isn't a git repository.", "and": "stop"},
        {"when": {"falsy": "{ok}"}, "do": "say", "text": "git status failed: {error_summary}", "and": "stop"},
        {"when": {"falsy": "{lines}"}, "do": "say", "text": "No uncommitted changes in {path|show}.", "and": "stop"},
        {"do": "say", "text": "{lines|count} uncommitted change{lines|count|s} in {path|show}:\n{lines|lines}"},
    ]),
    Procedure(id="git_log", act="git_log", steps=[
        {"do": "call", "proc": "resolve", "with": {"ref": "{slot.target}", "want": "directory", "what": "folder"}, "bind": {"path": "path"}},
        {"when": {"missing": "{path}"}, "do": "stop"},
        {"do": "run", "command": "git -C {path|q} log --oneline -n 10", "why": "git log in {path|show}"},
        {"do": "focus", "path": "{path}", "kind": "directory"},
        {"do": "compute", "prim": "contains_text", "args": {"haystack": "{out}", "needle": "does not have any commits"}, "as": "fresh"},
        {"when": {"truthy": "{fresh_found}"}, "do": "say", "text": "{path|show} has no commits yet.", "and": "stop"},
        {"when": {"falsy": "{ok}"}, "do": "say", "text": "git log failed: {error_summary}", "and": "stop"},
        {"when": {"falsy": "{lines}"}, "do": "say", "text": "{path|show} has no commits yet.", "and": "stop"},
        {"do": "say", "text": "Latest commits in {path|show}:\n{lines|lines}"},
    ]),
]

BY_ACT = {p.act: p for p in PROCEDURES if p.act}
BY_ID = {p.id: p for p in PROCEDURES}
